import { defineConfig } from "tsup";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: false,
  clean: false,
  sourcemap: false,
  bundle: true,
  minify: false,
  target: "node18",
  platform: "node",
  outDir: "dist",
  outExtension: () => ({ js: ".js" }),
  // Bundle all dependencies except Node.js built-ins and Anthropic SDK packages
  external: [
    // Node.js built-ins
    "fs",
    "path",
    "crypto",
    "os",
    "url",
    "util",
    "events",
    "stream",
    "buffer",
    "process",
    "child_process",
    "worker_threads",
    "cluster",
    "net",
    "http",
    "https",
    "tls",
    "zlib",
    "querystring",
    "assert",
    "console",
    "timers",
    "dns",
    // External modules that need access to their original file structure
    "@anthropic-ai/claude-agent-sdk",
    "@anthropic-ai/sdk",
  ],
  // Add shebang for executable
  banner: {
    js: "#!/usr/bin/env node\n",
  },
  // Bundle most dependencies but exclude those that need to remain external
  noExternal: [/^(?!@anthropic-ai\/(claude-agent-sdk|sdk)$).*/],
  // Auto-generate the Convex bundle after build
  onSuccess: async () => {
    const workerBundlePath = join(__dirname, "dist/index.js");
    const outputPath = join(__dirname, "../convex/lib/workerBundle.ts");

    try {
      console.log("Reading worker bundle from:", workerBundlePath);
      const bundleContent = readFileSync(workerBundlePath, "utf-8");

      const output = `// Auto-generated file - do not edit manually
// Generated by packages/worker/tsup.config.ts
// Source: packages/worker/dist/index.js

export function getWorkerSource(): string {
  return ${JSON.stringify(bundleContent)};
}

export const WORKER_BUNDLE_SIZE = ${Buffer.byteLength(bundleContent, "utf-8")};
`;

      writeFileSync(outputPath, output, "utf-8");
      console.log("✓ Worker bundle embedded successfully");
      console.log("  Output:", outputPath);
      console.log("  Size:", (Buffer.byteLength(bundleContent, "utf-8") / 1024).toFixed(2), "KB");
    } catch (error) {
      console.error("✖ Failed to bundle worker:", error);
      throw error;
    }
  },
});
